export const mcqs = [
  {
    id: 1,
    question: 'What is the Chakma word for "water"?',
    options: ['Doya', 'Bina', 'Dhana', 'Biyu'],
    correctAnswer: 'Doya',
  },
  {
    id: 2,
    question: 'How do you say "hello" in Chakma?',
    options: ['Namoshkar', 'Haila', 'Bujang', 'Hoye'],
    correctAnswer: 'Haila',
  },
  {
    id: 3,
    question: 'Which letter represents the Chakma alphabet "𑄝"?',
    options: ['ba', 'ga', 'ma', 'na'],
    correctAnswer: 'ba',
  },
  {
    id: 4,
    question: 'What does "Ama" mean in Chakma?',
    options: ['Father', 'Mother', 'Brother', 'Sister'],
    correctAnswer: 'Mother',
  },
  {
    id: 5,
    question: 'What is "Doya" used for?',
    options: ['Drink', 'Wash', 'Bath', 'All of the above'],
    correctAnswer: 'All of the above',
  },
  {
    id: 6,
    question: 'How do you say "thank you" in Chakma?',
    options: ['Boori', 'Aphom', 'Dhonobad', 'Zoron'],
    correctAnswer: 'Boori',
  },
  {
    id: 7,
    question: 'What is the Chakma word for "rice"?',
    options: ['Dha', 'Guri', 'Pora', 'Bhat'],
    correctAnswer: 'Bhat',
  },
  {
    id: 8,
    question: 'What does "Zoron" mean?',
    options: ['Sit down', 'Come', 'Go', 'Run'],
    correctAnswer: 'Sit down',
  },
  {
    id: 9,
    question: 'Which script is used in Chakma language?',
    options: ['Latin', 'Bengali', 'Chakma', 'Devanagari'],
    correctAnswer: 'Chakma',
  },
  {
    id: 10,
    question: 'What does "Buli" mean?',
    options: ['Food', 'Language', 'Work', 'Money'],
    correctAnswer: 'Language',
  },
  {
    id: 11,
    question: 'Translate "Father" into Chakma.',
    options: ['Baba', 'Ama', 'Abba', 'Acha'],
    correctAnswer: 'Baba',
  },
  {
    id: 12,
    question: 'Which of the following is a Chakma consonant?',
    options: ['𑄘', 'ক', 'क', 'గ'],
    correctAnswer: '𑄘',
  },
  {
    id: 13,
    question: 'How do you write "moon" in Chakma?',
    options: ['Soma', 'Chanda', 'Tara', 'Luma'],
    correctAnswer: 'Chanda',
  },
  {
    id: 14,
    question: 'What is the meaning of "Tala"?',
    options: ['Sky', 'Earth', 'Star', 'Sun'],
    correctAnswer: 'Earth',
  },
  {
    id: 15,
    question: 'What does "Anu" mean?',
    options: ['Yes', 'No', 'Maybe', 'Later'],
    correctAnswer: 'Yes',
  },
  {
    id: 16,
    question: 'Which number is "Ek" in Chakma?',
    options: ['1', '2', '3', '4'],
    correctAnswer: '1',
  },
  {
    id: 17,
    question: 'How do you write the Chakma vowel "aa"?',
    options: ['𑄃', '𑄄', '𑄅', '𑄆'],
    correctAnswer: '𑄄',
  },
  {
    id: 18,
    question: 'Translate "Friend" into Chakma.',
    options: ['Dugoi', 'Thap', 'Mitro', 'Zara'],
    correctAnswer: 'Mitro',
  },
  {
    id: 19,
    question: 'What does "Dugoi" mean?',
    options: ['Together', 'Two people', 'Alone', 'Couple'],
    correctAnswer: 'Together',
  },
  {
    id: 20,
    question: 'Chakma is primarily spoken in which country?',
    options: ['India', 'Bangladesh', 'Myanmar', 'All of the above'],
    correctAnswer: 'All of the above',
  },
  {
    id: 21,
    question: 'What does "Thui" mean?',
    options: ['Eat', 'Drink', 'Sit', 'Stand'],
    correctAnswer: 'Eat',
  },
  {
    id: 22,
    question: 'What is "Boya" in Chakma?',
    options: ['Fire', 'Light', 'Water', 'Wind'],
    correctAnswer: 'Fire',
  },
  {
    id: 23,
    question: 'How do you say "I am fine" in Chakma?',
    options: ['Bujang’, ‘Thik achi’, ‘Ham bhalo’, ‘Bhalo asi'],
    correctAnswer: 'Bhalo asi',
  },
  {
    id: 24,
    question: 'Which of these is a Chakma greeting?',
    options: ['Nomoshkar', 'Haila', 'Assalamu Alaikum', 'Vanakkam'],
    correctAnswer: 'Haila',
  },
  {
    id: 25,
    question: 'What is the meaning of "Seyna"?',
    options: ['Why', 'Where', 'When', 'How'],
    correctAnswer: 'Why',
  },
  {
    id: 26,
    question: 'What does "Ajana" mean?',
    options: ['Today', 'Tomorrow', 'Yesterday', 'Now'],
    correctAnswer: 'Today',
  },
  {
    id: 27,
    question: 'Which is a traditional Chakma musical instrument?',
    options: ['Dotara', 'Flute', 'Dul', 'Dhol'],
    correctAnswer: 'Dul',
  },
  {
    id: 28,
    question: 'Translate "Dog" into Chakma.',
    options: ['Gura', 'Kukkur', 'Tuta', 'Pora'],
    correctAnswer: 'Kukkur',
  },
  {
    id: 29,
    question: 'What does "Bucha" mean?',
    options: ['Understand', 'Speak', 'Write', 'Read'],
    correctAnswer: 'Understand',
  },
  {
    id: 30,
    question: 'Which month is "Baisakh" in Chakma calendar?',
    options: ['First', 'Third', 'Seventh', 'Last'],
    correctAnswer: 'First',
  },
  {
    id: 31,
    question: 'How do you say “School” in Chakma?',
    options: ['Thunlai', 'Sikhla', 'Skul', 'Pathshaala'],
    correctAnswer: 'Thunlai',
  },
  {
    id: 32,
    question: 'What is "Zodi" in Chakma?',
    options: ['Star', 'Moon', 'Sun', 'Night'],
    correctAnswer: 'Star',
  },
  {
    id: 33,
    question: 'Chakma belongs to which language family?',
    options: ['Indo-Aryan', 'Sino-Tibetan', 'Dravidian', 'Austroasiatic'],
    correctAnswer: 'Indo-Aryan',
  },
  {
    id: 34,
    question: 'What does "Juna" mean?',
    options: ['Old', 'New', 'Young', 'Fast'],
    correctAnswer: 'Old',
  },
  {
    id: 35,
    question: 'How do you ask "How are you?" in Chakma?',
    options: ['Tumi kamon aso?', 'Hani bo to?', 'Bhalo asi?', 'Seyna tumi?'],
    correctAnswer: 'Hani bo to?',
  },
  {
    id: 36,
    question: 'What does "Pura" mean?',
    options: ['Book', 'House', 'School', 'Garden'],
    correctAnswer: 'Book',
  },
  {
    id: 37,
    question: 'Which Chakma word means "write"?',
    options: ['Likha', 'Parha', 'Bucha', 'Sunna'],
    correctAnswer: 'Likha',
  },
  {
    id: 38,
    question: 'What does "Zima" mean in Chakma?',
    options: ['Rain', 'Snow', 'Thunder', 'Cloud'],
    correctAnswer: 'Rain',
  },
  {
    id: 39,
    question: 'What is the Chakma word for "Sun"?',
    options: ['Roti', 'Zodi', 'Soma', 'Suruj'],
    correctAnswer: 'Soma',
  },
  {
    id: 40,
    question: 'Which is the Chakma word for "You"?',
    options: ['Bo', 'To', 'Ami', 'Apni'],
    correctAnswer: 'To',
  },
];
